services:
  loveline-backend:
    container_name: loveline-backend
    ports:
      - "1331:8080"
    image: igoraxa/loveline-backend
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.datasource.url": "jdbc:mysql://172.17.0.1:3306/loveline",
        "spring.datasource.username": "loveline",
        "spring.datasource.password": "loveline",
        "spring.servlet.multipart.max-file-size": "10MB",
        "spring.servlet.multipart.max-request-size": "10MB"
      }'
